### PR TITLE
Update NBA player data and make variable names consistent

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Comment by joel-costigliola** [comment]
fair enough :)
I wouln't mind if you wanted to add Giannis ;-)

**Comment by geoand** [comment]
Aha, great idea! I wouldn't mind that one little bit either (not least for the fact that he is a fellow country-man :)).
I will rebase the PR  in a few minutes with Giannis included :)

**Comment by geoand** [comment]
Done :)

**Comment by joel-costigliola** [comment]
Integrated thanks @geoand !

**Comment by geoand** [comment]
You are most welcome!

**Pull request closed without merging**
